// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrjckgcpcmtvgfkhxewc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyamNrZ2NwY210dmdma2h4ZXdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1MzQ2MTksImV4cCI6MjA3MjExMDYxOX0.lP3zS_n7t1twSyZPdEGP87c1s1KWafqyNQpHb1sylOk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});